# 服务器配置
server:
  port: "8888"  # 服务器端口号

# 运行模式配置
mode: "prod"     # 运行模式，可选：prod/dev/test

# 日志配置
log:
  level: "info"  # 日志级别，可选：debug/info/warn/error/fatal/panic

# 管理员账户配置
admin:
  username: "admin"  # 管理员用户名
  password: "admin"  # 管理员密码

# 数据库配置
database:
  driver: "sqlite"       # 数据库驱动，支持：sqlite/postgres
  path: "./data/data.db" # SQLite数据库文件路径(仅sqlite驱动需要)
  host: "postgres"       # 数据库主机地址
  port: 5432             # 数据库端口
  user: "spage"          # 数据库用户名
  password: "spage"      # 数据库密码
  dbname: "spage"        # 数据库名称
  sslmode: "disable"     # SSL模式(对于PostgreSQL)

# 验证码配置
captcha:
  type: "disable"     # 验证码类型，支持：turnstile/recaptcha/hcaptcha/mcaptcha/disable
  site-key: ""        # 验证码站点密钥
  secret-key: ""      # 验证码密钥
  url: ""             # mcaptcha验证码URL

# 邮箱配置
email:
  enable: false       # 是否启用邮箱功能
  username: ""        # 邮箱用户名
  address: ""         # 邮箱地址
  host: ""            # 邮箱服务器地址
  port: "465"         # 邮箱服务器端口
  password: ""        # 邮箱密码
  ssl: true           # 是否启用SSL

# Token配置
token:
  secret: "none-secret"         # JWT密钥
  expire: 86400                 # Token过期时间(秒)，默认24小时
  refresh-expire: 518400         # 刷新Token过期时间(秒)，默认6天
  
# File配置
file:
  release-path: "./data/release"    # 发布文件保存路径