name: Build & Publish All-in-One

on:
  push:
    branches: [main]
    tags: [v*]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BIN_NAME: spage
  BIN_OUT: build

concurrency:
  group: "build-aio"
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

          - goos: freebsd
            goarch: amd64
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: 386
          - goos: freebsd
            goarch: arm

          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm
          - goos: linux
            goarch: ppc64le
          - goos: linux
            goarch: s390x

          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build frontend
        run: |
          cd web-src
          npm install pnpm -g
          pnpm install
          pnpm build
          cp -r out/* ../static/dist/

      - name: Build Go binary
        continue-on-error: true
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p ${{ env.BIN_OUT }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BIN_OUT="${{ env.BIN_OUT }}/${{ env.BIN_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
          else
            BIN_OUT="${{ env.BIN_OUT }}/${{ env.BIN_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          fi
          go build -o $BIN_OUT ./cmd/server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            ${{ env.BIN_OUT }}/${{ env.BIN_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}*

  publish:
    name: Publish Artifacts & Images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts for release
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.BIN_NAME }}-*
          path: ${{ env.BIN_OUT }}

      - name: Prepare binaries for Docker build
        run: |
          set -e
          ls -l build/
          # 支持的 Docker 架构
          for arch in amd64 arm64 386 arm ppc64le s390x; do
            if [ -f build/spage-linux-$arch/spage-linux-$arch ]; then
              mkdir -p build/linux-$arch
              cp build/spage-linux-$arch/spage-linux-$arch build/linux-$arch/spage
            fi
          done
          ls -l build/linux-amd64/

      - name: Set version/tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            TAG="${VERSION}"
            NIGHTLY="false"
          else
            VERSION="${GITHUB_SHA}"
            TAG="nightly"
            NIGHTLY="true"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "nightly=${NIGHTLY}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: reg.liteyuki.org
          username: ${{ secrets.LITEYUKIREG_USER }}
          password: ${{ secrets.LITEYUKIREG_TOKEN }}

      - name: Build & Push to GHCR & DockerHub & LCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/liteyukistudio/${{ env.BIN_NAME }}:${{ steps.version.outputs.tag }}
            docker.io/liteyukistudio/${{ env.BIN_NAME }}:${{ steps.version.outputs.tag }}
            reg.liteyuki.org/${{ env.BIN_NAME }}/${{ env.BIN_NAME }}:${{ steps.version.outputs.tag }}
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm

      - name: Publish GitHub Release
        if: ${{ steps.version.outputs.nightly == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          body: |
            Release ${{ steps.version.outputs.tag }}
            Built from tag ${{ steps.version.outputs.tag }}
          files: |
            ${{ env.BIN_OUT }}/${{ env.BIN_NAME }}-*
            ${{ env.BIN_OUT }}/${{ env.BIN_NAME }}-*.exe
