on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    # ...build steps...

  publish-nightly:
    if: github.ref == 'refs/heads/main'
    # ...上传artifact和nightly镜像...

  publish-release:
    if: startsWith(github.ref, 'refs/tags/v')
    # ...发布release和tag镜像...