name: Build SPAGE with CGO

on:
  push:
    tags:
      - v*  # 只有在推送标签时触发，例如 v1.0.0

jobs:
  build:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Install C dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build frontend
        run: |
          git clone https://github.com/LiteyukiStudio/spage-web
          cd spage-web
          npm install pnpm@latest -g
          pnpm install && pnpm build
          mv dist/** ../static/dist

      - name: Build with CGO
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p build
          go build -o build/spage cmd/server/main.go

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: spage-linux-amd64
          path: build/spage
          if-no-files-found: error

  release:
    name: Create and Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Extract tag name
        id: extract_tag
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spage-linux-amd64
          path: build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          release_name: SPAGE ${{ steps.extract_tag.outputs.tag_name }}
          body: |
            SPAGE release ${{ steps.extract_tag.outputs.tag_name }}
            Binary built with CGO_ENABLED=1 for Linux amd64
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/spage
          asset_name: spage-linux-amd64
          asset_content_type: application/octet-stream